### PR TITLE
Python3 Refactor

### LINKED ISSUE #1: Several urllib errors with current Python version.
Script does not work as new urllib syntax have changed.

### PR DESCRIPTION
**Pull request by martialblog**
- Used lib2to3 for add Python 3 support. Fixes #1 
- Added version to --help output

### CODE REVIEW

**Comment by RincewindsHat** [comment]
Please change the shebang to `python3` (instead of `python`). On Debian Systems `python` does not exist anymore to prevent confusion.

**Comment by martialblog** [comment]
@RincewindsHat Done

**Comment by RincewindsHat** [comment]
@martialblog:  Fixed some differences in the request modules:

```
diff --git a/notify_rocketchat.py b/notify_rocketchat.py
index 8a16310..a753501 100755
--- a/notify_rocketchat.py
+++ b/notify_rocketchat.py
@@ -45,9 +45,9 @@ def web_response(request):

 def chat_login(args):
     request = create_request(args.url + '/api/v1/login')
-    request.add_data(json.dumps({
+    request.data = (json.dumps({
         'user': args.user, 'password': args.password
-    }))
+    })).encode()

     response = web_response(request)

@@ -65,11 +65,11 @@ def chat_message(data, args):
     request.add_header('X-Auth-Token', data['authToken'])
     request.add_header('X-User-Id', data['userId'])

-    request.add_data(json.dumps({
+    request.data = (json.dumps({
         'text': args.message,
         'channel': args.channel

-    }))
+    })).encode()

     response = web_response(request)
```
could you integrate them?

**Comment by martialblog** [comment]
@RincewindsHat I just added the changes.

**Comment by RincewindsHat** [comment]
```
  File "/......./notify_rocketchat/./notify_rocketchat.py", line 48, in chat_login
    request.data(json.dumps({
TypeError: 'NoneType' object is not callable
```

```
-   request.data(json.dumps({
+   request.data = (json.dumps({
```

:-)

**Comment by martialblog** [comment]
:facepalm: I'm just gonna write some unittests...

**Comment by martialblog** [comment]
Ok now we should be good

**Pull request merged**
